
package mx.gob.imss.consultamatricula;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsConsultaSITSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsConsultaSITSoap {


    /**
     * 
     * @param delegacion
     * @param matricula
     * @param curp
     * @param nss
     * @return
     *     returns mx.gob.imss.consultamatricula.ConsultaMatriculaResponse.ConsultaMatriculaResult
     */
    @WebMethod(operationName = "ConsultaMatricula", action = "http://tempuri.org/ConsultaMatricula")
    @WebResult(name = "ConsultaMatriculaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaMatricula", targetNamespace = "http://tempuri.org/", className = "mx.gob.imss.consultamatricula.ConsultaMatricula")
    @ResponseWrapper(localName = "ConsultaMatriculaResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.imss.consultamatricula.ConsultaMatriculaResponse")
    public mx.gob.imss.consultamatricula.ConsultaMatriculaResponse.ConsultaMatriculaResult consultaMatricula(
        @WebParam(name = "Matricula", targetNamespace = "http://tempuri.org/")
        String matricula,
        @WebParam(name = "Delegacion", targetNamespace = "http://tempuri.org/")
        String delegacion,
        @WebParam(name = "NSS", targetNamespace = "http://tempuri.org/")
        String nss,
        @WebParam(name = "CURP", targetNamespace = "http://tempuri.org/")
        String curp);

}
