
package mx.gob.imss.consultamatricula;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsConsultaSIT", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.100.6.60/ServiciosWebSIT/wsConsultaSIT.asmx?WSDL")
public class WsConsultaSIT
    extends Service
{

    private final static URL WSCONSULTASIT_WSDL_LOCATION;
    private final static WebServiceException WSCONSULTASIT_EXCEPTION;
    private final static QName WSCONSULTASIT_QNAME = new QName("http://tempuri.org/", "wsConsultaSIT");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.100.6.60/ServiciosWebSIT/wsConsultaSIT.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCONSULTASIT_WSDL_LOCATION = url;
        WSCONSULTASIT_EXCEPTION = e;
    }

    public WsConsultaSIT() {
        super(__getWsdlLocation(), WSCONSULTASIT_QNAME);
    }

    public WsConsultaSIT(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONSULTASIT_QNAME, features);
    }

    public WsConsultaSIT(URL wsdlLocation) {
        super(wsdlLocation, WSCONSULTASIT_QNAME);
    }

    public WsConsultaSIT(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONSULTASIT_QNAME, features);
    }

    public WsConsultaSIT(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsConsultaSIT(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsConsultaSITSoap
     */
    @WebEndpoint(name = "wsConsultaSITSoap")
    public WsConsultaSITSoap getWsConsultaSITSoap() {
        return super.getPort(new QName("http://tempuri.org/", "wsConsultaSITSoap"), WsConsultaSITSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsConsultaSITSoap
     */
    @WebEndpoint(name = "wsConsultaSITSoap")
    public WsConsultaSITSoap getWsConsultaSITSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wsConsultaSITSoap"), WsConsultaSITSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONSULTASIT_EXCEPTION!= null) {
            throw WSCONSULTASIT_EXCEPTION;
        }
        return WSCONSULTASIT_WSDL_LOCATION;
    }

}
